apiVersion: v1
kind: Service
metadata:
  name: devx-kafka
  namespace: devx
  labels:
    app: devx-kafka-messagebus
spec:
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: zookeeper
    port: 2181
    targetPort: 2181
    protocol: TCP
  selector:
    app: devx-kafka-messagebus

  externalIPs: ["192.168.99.100"]
