kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: parser-pod
  namespace: devx
spec:
  template:
    metadata:
      labels:
        app: parser-pod
    spec:
      containers:
      - name: parser-pod
        image: devx/parser:v1
        env:
        - name: DEVX_KAFKA_TOPIC
          value: "test"
        - name: DEVX_KAFKA_BOOTSTRAP_SERVERS
          value: "172.17.0.4:9092"
        - name: DEVX_KAFKA_CONSUMER_NAME
          value: "parserConsumer"