apiVersion: v1
kind: Service
metadata:
  name: devx-mockserver
  namespace: devx
  labels:
    app: devx-mockserver
spec:
  ports:
  - port: 18080
    targetPort: 8080
    protocol: TCP
  selector:
    app: mockserver-pod

  externalIPs: ["192.168.99.100"]