kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mockserver-pod
  namespace: devx
spec:
  template:
    metadata:
      labels:
        app: mockserver-pod
    spec:
      containers:
      - name: mockserver-pod
        image: devx/mockserver:v1
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: mockdata-store
            mountPath: /mock/data
      volumes:
      - name: mockdata-store
        hostPath:
          path: /data/mock
          type: Directory