apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: devx
  labels:
    io.kompose.service: web
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: web
  type: NodePort